version: "3.3"
services:
  web:
    build: .
    image: hovig/python-ml-pipeline
    command: python pull_data.py
    depends_on:
      - es
    ports:
      - 5000:5000
    volumes:
      - .:/ml
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
volumes:
    esdata1:
      driver: local
